steps:
  # Krok 1: Zbuduj obraz Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-central2-docker.pkg.dev/$PROJECT_ID/my-app/demo-app:$SHORT_SHA',
      '.'
    ]

# Krok 2: Wypchnij obraz do Artifact Registry
images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/my-app/demo-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY # Dodaj tę linię
